Lab8/urls.py
from django.contrib import admin
from django.urls import path, include
import Story8.urls as Story8
import story9.urls as story9
import story10.urls as story10
import story11.urls as story11
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lab8/', include(('Story8.urls', 'Story8'), namespace = "story6")),
    path('lab9/', include(('story9.urls', 'story9'), namespace = "story9")),
    path('lab10/', include(('story10.urls', 'story10'), namespace = "story10")),
    path('lab11/', include(('story11.urls', 'story11'), namespace = "story11")),
    path('auth/', include('social_django.urls', namespace='social')),
    
]

Story8/urls.py
from django.conf.urls import url
from .views import profile

urlpatterns = [
	url('', profile, name = 'profile'),
]

story10/urls.py
from django.urls import path
from .views import *

urlpatterns = [
	path('', subscribe, name="form"),
	path('addSubscribe/', addSub, name="addSubscribe"),
	path('validasi', validasi, name="validasi"),
	path('unsubscribe/', unsubscribe, name='unsubscribe'),
	path('data', data, name = 'data'),
	path('delObject', delObject, name = 'delObject')

]

story11/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views
from .views import home
from django.conf import settings

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^auth/', include('social_django.urls', namespace='social')),  # <- Here
    url(r'^$', home, name='home'),
]

story9/urls.py
from django.urls import path
from .views import table, data, data_science, table1, index
from django.conf.urls import url, include
from django.contrib.auth import views
from .views import *
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from .views import home
from django.conf import settings

urlpatterns = [
	path('', table, name = 'table'),
	path('data', data, name = 'data'),
	path('data_science', data_science, name = 'data_science'),
	path('quilting', table1, name = 'table1'),
]

Story8/models.py
from django.db import models
from django.utils import timezone
from datetime import date
# Create your models here.

story10/models.py
from django.db import models

# Create your models here.
class Model_Subscribe(models.Model):
	nama = models.CharField(max_length=200)
	email = models.EmailField(unique = True)
	password = models.CharField(max_length = 200)

story11/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

Story8/forms.py
from django import forms
import datetime
class Form_Subscribe(forms.Form):

    error_messages = {
        'required': 'Please type',
    }

    nama_attrs = {
        'type': 'text',
        'placeholder' : 'Nama Lengkap',
        'class' : 'form-control',
    }

    email_attrs = {
        'type': 'email',
        'id' : 'email',
        'placeholder' : 'Email',
        'class' : 'form-control',
    }

    password_attrs = {
        'type': 'password',
        'placeholder': 'Password',
        'class' : 'form-control'
    }

    nama = forms.CharField(label='Nama Lengkap', required=True, widget=forms.TextInput(attrs = nama_attrs))
    email = forms.EmailField(label='Alamat Email', required=True, widget=forms.TextInput(attrs = email_attrs))
    password = forms.CharField(required=True, widget = forms.PasswordInput(attrs = password_attrs))

story10/forms.py
from django import forms
import datetime
class Form_Subscribe(forms.Form):

    error_messages = {
        'required': 'Please type',
    }

    nama_attrs = {
        'type': 'text',
        'id': 'nama',
        'placeholder' : 'Nama Lengkap',
        'class' : 'form-control',
    }

    email_attrs = {
        'type': 'email',
        'id' : 'email',
        'placeholder' : 'Email',
        'class' : 'form-control',
    }

    password_attrs = {
        'type': 'password',
        'id': 'password',
        'placeholder': 'Password',
        'class' : 'form-control'
    }

    nama = forms.CharField(label='Nama Lengkap', required=True, widget=forms.TextInput(attrs = nama_attrs))
    email = forms.EmailField(label='Alamat Email', required=True, widget=forms.TextInput(attrs = email_attrs))
    password = forms.CharField(required=True, widget = forms.PasswordInput(attrs = password_attrs))


class Form_Unsubscribe(forms.Form):

    error_messages = {
        'required': 'Please type',
    }

    email_attrs = {
        'type': 'email',
        'id' : 'email',
        'placeholder' : 'Email',
        'class' : 'form-control',
    }

    email = forms.EmailField(label='Alamat Email', required=True, widget=forms.TextInput(attrs = email_attrs))
    

Story8/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.http import JsonResponse
from django.conf import settings	
from django.core import serializers
import requests
import json


response = {}

# Create your views here.
def profile(request):
	return render(request, 'profil.html')

story10/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.http import JsonResponse
from django.conf import settings	
from django.core import serializers
import requests
import json
from .models import *
from .forms import *

# Create your views here.
def subscribe(request):
	form = Form_Subscribe(request.POST or None)
	return render(request, 'formsubscribe.html', {'form':form})

def unsubscribe(request):
	form = Form_Unsubscribe(request.POST or None)
	return render(request, 'formunsubscribe.html', {'form':form})

def data(request):
	getJson = requests.get('http://naufaldi-lab8.herokuapp.com/lab10/addSubscribe/').json()
	return JsonResponse(getJson)

@csrf_exempt
def addSub(request):
	if (request.method == 'POST'):
		enctype = "multipart/form-data"
		nama = request.POST['nama']
		email = request.POST['email']
		password = request.POST['password']

		subscriber = Model_Subscribe(nama = nama, email = email, password = password)
		subscriber.save()
		
		data = getObject(subscriber)
		return HttpResponse(data)
	else:
		sub = Model_Subscribe.objects.all().values()
		data = list(sub)
		return JsonResponse({'items':data}, safe = False)

@csrf_exempt
def validasi(request):
	enctype = "multipart/form-data"
	email = request.POST.get('email')
	data = {
		'is_taken':Model_Subscribe.objects.filter(email=email).exists()
		}
	return JsonResponse(data)

def getObject(obj):
	data = serializers.serialize('json', [obj,])
	struct = json.loads(data)
	data = json.dumps(struct[0]["fields"])
	return data

@csrf_exempt
def delObject(request):
	email = request.POST.get('email')
	nama = Model_Subscribe.objects.filter(email = email)
	data = list(nama)
	Model_Subscribe.objects.filter(email = email).delete()
	return JsonResponse({'items':data}, safe = False)

story11/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

story9/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.conf import settings
import requests
import json

# Create your views here.
def table(request):
	return render(request, 'books.html')

def data(request):
	getJson = requests.get('https://www.googleapis.com/books/v1/volumes?q=programming').json()
	return JsonResponse(getJson)

def data_science(request):
	getJson = requests.get('https://www.googleapis.com/books/v1/volumes?q=quilting').json()
	return JsonResponse(getJson)

def table1(request):
	return render(request, 'books1.html')

def index(request):
	return render(request, 'index.html')

def home(request):
	return render(request, 'home.html')

Story8/templates/profil.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <title>story 8 naufaldi</title>
    <link rel = "stylesheet" type = "text/css" href = "{%static 'css/styling.css' %}"/>
    <link rel = "stylesheet" type = "text/css" href = "{%static 'css/switchstyle.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="{% static 'js/jscript.js' %}"></script>
</head>
<body class = "loading" id="background" onload="nightmode()">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <div class="dots-loader"></div>
<div class="container">
    <div id = "nightmode">
        <label class="switch">
            <input type="checkbox" onclick="nightmode()">
            <span class="slider"></span>
        </label>
        Night Mode
    </div>
</div>
<div class="container">
    <div class="row">
    <h1 id = "font">My Profile<br></h1>
    <!-- Contenedor -->
    <ul id="accordion" class="accordion">
    <li>
<div class="col col_4 iamgurdeep-pic">
<img class="img-responsive iamgurdeeposahan" alt="iamgurdeeposahan" src="https://preview.ibb.co/enPAq0/Naufaldi-Athallah-Rifqi-olim.jpg" title="Foto ganteng">
<div class="edit-pic">
<a href="https://www.facebook.com/naufaldifqi" target="_blank" class="fa fa-facebook"></a>
<a href="https://www.instagram.com/naufaldirfq/" target="_blank" class="fa fa-instagram"></a>
<a href="https://twitter.com/naufaldirfq" target="_blank" class="fa fa-twitter"></a>



</div>
<div class="username">
    <h2>Naufaldi Athallah Rifqi <br><small><i class="fa fa-map-marker"></i> Indonesia (Depok)</small></h2>
    <p><i class="fa fa-briefcase"></i> Faculty of Computer Science Universitas Indonesia.</p>
    
    <a href="https://www.facebook.com/naufaldifqi" target="_blank" class="btn-o"> <i class="fa fa-user-plus"></i> Add Friend </a>
    <a href="https://www.instagram.com/naufaldirfq/" target="_blank"  class="btn-o"> <i class="fa fa-plus"></i> Follow IG</a>
    
   
</div>
</div>
        
    </li>
        <li>
            <div class="link"><i class="fa fa-globe"></i>About<i class="fa fa-chevron-down"></i></div>
            <ul class="submenu">
                <li><a href="#"><i class="fa fa-calendar left-none"></i> Date of Birth : 02/16/1999</a></li>
                <li><a href="#">Address : Indonesia, Depok</a></li>
                <li><a href="mailto:naufalrifqi1602@gmail.com">Email : naufalrifqi1602@gmail.com</a></li>
                <li><a href="#">Phone : +62 87887662027</a></li>
            </ul>
        </li>
        <li>
            <div class="link"><i class="fa fa-book"></i>Experiences<i class="fa fa-chevron-down"></i></div>
            <ul class="submenu">
                <li><a href="#"><span class="tags">Universitas Indonesia</span> <span class="tags">Faculty of Computer Science</span> <span class="tags">Staff of Event CS League 2018</span> <span class="tags">Staff of Seminar COMPFEST X</span>
                <span class="tags">Staff of Athletic Department BEM Fasilkom UI</span> <span class="tags">Staff of Basketball Universiade 2017</span> <span class="tags">Project Officer of CS League 2019</span></a>
            </ul>
        </li>
        <li>
            <div class="link"><i class="fa fa-futbol-o"></i>Activities<i class="fa fa-chevron-down"></i></div>
            <ul class="submenu">
                <li><a href="#"><span class="tags">Belajar</span> <span class="tags">Makan</span> <span class="tags">Tidur</span> <span class="tags">Ngerjain tugas</span>
                <span class="tags">Begadang</span> <span class="tags">Minum Kopi</span> <span class="tags">Rapat</span></a>
            </ul>
        </li>
        <li>
            <div class="link"><i class="fa fa-trophy"></i>Achievements<i class="fa fa-chevron-down"></i></div>
            <ul class="submenu">
                <li><a href="#"><span class="tags">Finalist Business IT Case ITToday IPB 2018</span></a>
            </ul>
        </li>
        <li>
            <div class="link"><i class="fa fa-trophy"></i>Last but not least<i class="fa fa-chevron-down"></i></div>
            <ul class="submenu">
                <li><a href="/lab10/"><span class="tags">Please Subscribe</span></a>
            </ul>
        </li>

    </ul>
    </div>
    
 
    
</div>

Story8/templates/switch.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<link rel = "stylesheet" type = "text/css" href = "{%static 'css/switchstyle.css' %}"/>
	<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="{% static 'js/jscript.js' %}"></script>
	<title>Switch</title>
</head>
<body>
<div class="container">
    <div id = "nightmode">
        <label class="switch" onclick="nightmode()">
            <input type="checkbox">
            <span class="slider"></span>
        </label>
        Night Mode
    </div>
</div>
</body>
</html>

story10/templates/formsubscribe.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>Naufaldi Athallah</title>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{%static 'css/stylesheet.css' %}"/>

</head>
<body>
    <li><a href="/lab8/">Profile Page</a></li>
<section>
	<br>
  <div>
        <div style="width: 30%; margin: auto;" class = "jumbotron">
        	<div class="row" style="background-color: #b63b4d">
        	<h1 style="font-family: niramit; text-align: center; font-size: 40px" >Thanks for visiting!</h1>
        	<br>
        	</div>
        	<br>
            <form id="form" method="POST" onsubmit="window.submit()">
            {% csrf_token %}
            {{ form }}
            <button id="submit" type="submit" class="btn btn-lg btn-info" value="Subscribe" formnovalidate="formnovalidate">Subscribe</button>
            <li><a href="unsubscribe"> Unsubscribe</a></li>
          </form>
        </div>
    </div>
</section>
<div style="padding-top: 2%; margin-left: 10%;margin-right: 10%;">
        <table id="tabel" class="table table-light table-bordered table-hover" style="background-color: whitesmoke;">
            <tbody>
            <thead>
                <tr style="background-color: whitesmoke;">
                    <th scope="col" style="text-align: center;">Nama</th>
                    <th scope="col" style="text-align: center;">Email</th>
                </tr>
            </thead>
            </tbody>
        </table>    
    </div>
</div>
<script src="{% static 'js/subscriber.js' %}"></script>
<script type="text/javascript">
    console.log("hello")
    document.getElementById("submit").disabled = true;
    var email = document.getElementById('email');
    var time = null;

    email.onkeyup = function(e){
        clearTimeout(time);
        time = setTimeout(function(){
            $.ajax({
                method : 'POST',
                url : "{% url 'story10:validasi' %}",
                data : {
                    'email' : email.value
                },
                dataType : 'json',
                success: function(data){
                    if(data.is_taken){
                        console.log("udah ada")
                        alert("Email sudah terdaftar, masukkan email lain");
                        email.value = "";
                    }
                    else{
                        document.getElementById("submit").disabled = false;
                        console.log("data tidak ada")
                        alert("Email dapat digunakan");
                    }
                }
            })
        }, 1200);
    }

    function submit(){
        console.log("submit")
        event.preventDefault();
        register();
    }

    function register(){
        console.log("register")
        var nama = document.getElementById("text1");
        $.ajax({
            type : "POST",
            url : "{% url 'story10:addSubscribe' %}",
            dataType: 'json',
            data :{
                nama : $('#nama').val(),
                email : $('#email').val(),
                password : $('#password').val(),
            },
            success: function(result){
                alert($('#nama').val() + " telah terdaftar")
                window.location.reload();
            }
        })
    }
</script>

</body>
</html>

story10/templates/formunsubscribe.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>Naufaldi Athallah</title>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{%static 'stylesheet.css' %}"/>

</head>
<body>
    <li><a href="/lab8/">Profile Page</a></li>
<section>
	<br>
  <div>
        <div style="width: 30%; margin: auto;" class = "jumbotron">
        	<div class="row" style="background-color: #b63b4d">
        	<h1 style="font-family: niramit; text-align: center; font-size: 40px" >Input your email to unsubscribe</h1>
        	<br>
        	</div>
        	<br>
            <form id="form" method="POST" onsubmit="window.submit()">
            {% csrf_token %}
            {{ form }}
            <button href="/lab10" id="submit" type="submit" class="btn btn-lg btn-info" value="Subscribe" formnovalidate="formnovalidate">Unsubscribe</button>
          </form>
        </div>
    </div>
</section>
<script type="text/javascript">
    console.log("unsubscribe")
    document.getElementById("submit").disabled = true;
    var email = document.getElementById('email');
    var time = null;

    email.onkeyup = function(e){
        clearTimeout(time);
        time = setTimeout(function(){
            $.ajax({
                method : 'POST',
                url : "{% url 'story10:validasi' %}",
                data : {
                    'email' : email.value
                },
                dataType : 'json',
                
                success: function(data){
                    if(data.is_taken){
                        document.getElementById("submit").disabled = false;
                        console.log("udah ada");
                        alert("Email tersedia, silakan klik tombol unsubscribe");
                    }
                    else{
                        console.log("data tidak ada");
                        alert("Email tidak ada");
                        email.value = "";
                    }
                }
            })
        }, 1200);
    }

    function submit(){
        console.log("submit")
        event.preventDefault();
        delObj();
    }

    function delObj(){
        console.log("delete email")
        $.ajax({
            type : "POST",
            url : "{% url 'story10:delObject' %}",
            dataType: 'json',
            data :{
                email : $('#email').val(),
            },
            success: function(result){
                alert("berhasil unsubscribe")
                window.location.reload();
            }
        })
    }


    
</script>

</body>
</html>

story11/templates/home.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
{% block content %}
	{% if user.is_authenticated %}
             <p class="display-4">Hello, {{ user.username }}</p>
	{% else %}
             <a class="lead" href="{% url 'story11:login' %}">Log in</a>
	{% endif %}
{% endblock content %}
</body>
</html>

story9/templates/books.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/buttonstyle.css' %}"/>
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/searchstyle.css' %}"/>
	<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
	<title>Books</title>
</head>
<body>
	<br>
	<a href="/lab11/logout" onclick="signOut();">Sign out</a>
<script>
  function signOut() {
    var auth2 = gapi.auth2.getAuthInstance();
    auth2.signOut().then(function () {
      console.log('User signed out.');
    });
  }
</script>
{% block content %}
	{% if user.is_authenticated %}
             <p class="display-4">Hello, {{ user.first_name }}</p>
	{% else %}
             <a class="lead" href="{% url 'story11:login' %}">Log in</a>
	{% endif %}
{% endblock content %}
<div class="container">
    <div style="text-align: center;">
    	<img src="https://image.ibb.co/i2nUn0/star.png" style="text-align: center;" >
    	<h1 style="text-align: center;" id="counter">0</h1>
    <h1>Keyword</h1>
    <ul id="myUL">
  <li><a href="">Programming</a></li>
  <li><a href="/lab9/quilting">Quilting</a></li>
</ul>

<div style="padding-top: 2%; margin-left: 10%;margin-right: 10%;">
		<table id="tabel" class="table table-light table-bordered table-hover" style="background-color: whitesmoke;">
			<tbody>
			<thead>
				<tr style="background-color: whitesmoke;">
			    	<th scope="col" style="text-align: center;">Cover</th>
			    	<th scope="col" style="text-align: center;">Title</th>
			     	<th scope="col" style="text-align: center;">Authors</th>
			     	<th scope="col" style="text-align: center;">Publisher</th>
			      	<th scope="col" style="text-align: center;">Add to Favorites</th>
				</tr>
			</thead>
			</tbody>
		</table>	
	</div>
    </div>
    <script src="{% static 'js/func.js' %}"></script>
</body>
</html>

story9/templates/books1.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/buttonstyle.css' %}"/>
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/searchstyle.css' %}"/>
	<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
	<title>Books</title>
</head>
<body>
	<br>
	<a href="/lab11/logout" onclick="signOut();">Sign out</a>
<script>
  function signOut() {
    var auth2 = gapi.auth2.getAuthInstance();
    auth2.signOut().then(function () {
      console.log('User signed out.');
    });
  }
</script>
{% block content %}
	{% if user.is_authenticated %}
             <p class="display-4">Hello, {{ user.first_name }}</p>
	{% else %}
             <a class="lead" href="{% url 'story11:login' %}">Log in</a>
	{% endif %}
{% endblock content %}
<div class="container">
    <div style="text-align: center;">
    	<img src="https://image.ibb.co/i2nUn0/star.png" style="text-align: center;" >
    	<h1 style="text-align: center;" id="counter">0</h1>
    <h1>Keyword</h1>
    <ul id="myUL">
  <li><a href="/lab9/">Programming</a></li>
  <li><a href="/lab9/quilting">Quilting</a></li>
</ul>

<div style="padding-top: 2%; margin-left: 10%;margin-right: 10%;">
		<table id="tabel" class="table table-light table-bordered table-hover" style="background-color: whitesmoke;">
			<tbody>
			<thead>
				<tr style="background-color: whitesmoke;">
			    	<th scope="col" style="text-align: center;">Cover</th>
			    	<th scope="col" style="text-align: center;">Title</th>
			     	<th scope="col" style="text-align: center;">Authors</th>
			     	<th scope="col" style="text-align: center;">Publisher</th>
			      	<th scope="col" style="text-align: center;">Add to Favorites</th>
				</tr>
			</thead>
			</tbody>
		</table>	
	</div>
    </div>
    <script src="{% static 'js/func1.js' %}"></script>
</body>
</html>

story9/templates/search.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/searchstyle.css' %}"/>
</head>
<body>
<h2>Keyword</h2>

<!-- <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for names.." title="Type in a name"> -->

<ul id="myUL">
  <li><a href="/data/">Programming</a></li>
  <li><a href="/data_science/">Dilan</a></li>

<!--   <li><a href="#">Billy</a></li>
  <li><a href="#">Bob</a></li>

  <li><a href="#">Calvin</a></li>
  <li><a href="#">Christina</a></li>
  <li><a href="#">Cindy</a></li> -->
</ul>

<!-- <script>
function myFunction() {
    var input, filter, ul, li, a, i;
    input = document.getElementById("myInput");
    filter = input.value.toUpperCase();
    ul = document.getElementById("myUL");
    li = ul.getElementsByTagName("li");
    for (i = 0; i < li.length; i++) {
        a = li[i].getElementsByTagName("a")[0];
        if (a.innerHTML.toUpperCase().indexOf(filter) > -1) {
            li[i].style.display = "";
        } else {
            li[i].style.display = "none";
        }
    }
}
</script> -->

</body>
</body>
</html>